### ISSUE TITLE
Question on the provided Human3.6m dataset annotation

### ISSUE THREAD

**Issue by Lukikay** [lck1201/simple-effective-3Dpose-baseline#2]
Hi, many thanks for making this implement. I feel confused with the Human3.6m annotation you provided. Since the file size is almost twice larger than the original implement (https://github.com/una-dinosauria/3d-pose-baseline).  So do they have the same quantity 3D annotations? Looks your annotation data has entire four camera perspectives for each pose, and so are they from the original Human3.6 dataset? Cause I don't have the access to download the Human3.6 data yet and have no idea what they look like. Many thanks!

**Comment by lck1201** [comment]
Hi, it's an internal processed version, the same as origin. You can just follow my code to parse the dataset.

**Comment by Lukikay** [comment]
Okay, many thanks!
