### ISSUE TITLE
IndexError: list index out of range??

### ISSUE THREAD

**Issue by wongkwan** [lck1201/simple-effective-3Dpose-baseline#3]
When I test with your pre-training model, in line 52 of the main () function：logger. info ("Construct Dataset:", "config. DATASET. dbname [i]," "Dataset Path:", "config. DATASET. dataset_path [i]) will report errors: list index out of range.     I can't find the reason for the mistake. Can you help me solve it? If you can, thank you very much.

**Comment by lck1201** [comment]
Hi，the only reason should be `config. DATASET. dbname [i],config. DATASET. dataset_path [i]` index out of range. You can check config and index
