### ISSUE TITLE
Are training set and val set splitted correctly?

### ISSUE THREAD

**Issue by lucas946** [lck1201/simple-effective-3Dpose-baseline#4]
It seems that your code use subject 1, 5, 6, 7 and 8 to compose training set, and use subject 9,11 to compose val set. But in Human 3.6M official document, the training set is composed of S1, S7, S8, S9 and S11 (the val set is composed of S5 and S6), so is there any particular reason to do this?

**Comment by lck1201** [comment]
Hi, please refer to paper _A simple yet effective baseline for 3d human pose estimation_， I follow his evaluation

**Comment by lucas946** [comment]
Sorry, it's my fault, your setting is right. However, Human 3.6M dataset contains two type of 3d coordinates, which are D3_Positions_mono and D3_Positions_mono_universal and they are both in camera coordinate system. My question is, which type of 3d coordinates do you use?

**Comment by lck1201** [comment]
Hi, the dataset I use is the internal processed version, so I don't meet your problem. But I think you could back-project this two types of points to 2D plane to see which one should be used

**Comment by lucas946** [comment]
Thanks a lot, I will figure it out myself.
