### ISSUE TITLE
About the human 3. 6m dataset

### ISSUE THREAD

**Issue by lvandoit** [lck1201/simple-effective-3Dpose-baseline#5]
hi:
    First of all, congratulations on your good work. I am a graduate student inShanghai,At present, I am studying the direction of human posture detection, which requires the use of human 3.6m data set. Do you have any? Could you share it with me? Thank you for any reply @lck1201

**Comment by lck1201** [comment]
Hi, you could download dataset from HM3.6M official website, the size of entire dataset is more than 130GB, so it is difficult for me to share with you online. Sry

**Comment by lvandoit** [comment]
hi:
   I am very glad to receive your reply. I sent an email on the official website for the permission, but I haven't received any reply for a long time. I am a student of Shanghai research institute of Chinese academy of sciences, and now I need this data set for my research,so could you give me any guidance?thanks @lck1201

**Comment by lck1201** [comment]
Sorry, in fact I sent them emails but no reply. I don't know whether the website is being maintained or not. I think the only way now is to download dataset from other mirror source, or find someone who upload the dataset online.

**Comment by lvandoit** [comment]
So do you own the dataset? Could you share it with me please?I can give you my Baidu cloud.Also if you want ,i can pay you.
@lck1201

**Comment by lck1201** [comment]
Hi, I don't know whether it's legal for me to distribute their dataset. It's better to download from official source. Sorry I cannot help you. Further, the discussion is beyond the method itself, so I will close this issue.
