### ISSUE TITLE
Predict custom images

### ISSUE THREAD

**Issue by hundanLi** [lck1201/simple-effective-3Dpose-baseline#6]
How to predict my custom images, please?

**Comment by lck1201** [comment]
Hi, firstly you should use a 2D pose estimator on the image to get 2D pose result, then use the result as input of my system.

**Comment by hundanLi** [comment]
So how to use the custom 2D post result of a 2D estimator as input of your system, please?

**Comment by lck1201** [comment]
Basically, you need to organize 2D pose results as 32x2 array, normalization, and go through network. Please check https://github.com/lck1201/simple-effective-3Dpose-baseline/blob/master/lib/core/loader.py for data processor and loader, and https://github.com/lck1201/simple-effective-3Dpose-baseline/blob/master/lib/net_module.py for test pipeline.

**Comment by H19012** [comment]
So if our 2D estimator is inaccurate then will your model give inaccurate result compare to the ground truth.

**Comment by lck1201** [comment]
yes
